sudo: required
services:
  - docker

language: node_js
node_js:
  - '10'

before_install:
  - docker build -t tarvainen/abv-calculator .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
